### ISSUE TITLE
building spack

### ISSUE THREAD

**Issue by abidmalikwaterloo** [CODARcode/Example-Heat_Transfer#10]
Then edit ~/.spack/compilers.yaml (on Ubuntu, at least, it’s in ~/.spack/linux/compilers.yaml) and add /usr/bin/gfortran for both f77 and fcc

--------
I did all the steps. 
could not find compilers.yaml on my Ubuntu machine

**Comment by jychoi-hpc** [comment]
Just found that we need to execute the following line:
```spack compilers```
to create `compilers.yaml` initially if there is nothing. 

I have updated the document too.

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc 
Does Spack takecare of all dependencies?

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc 
The following doesn't work

spack install savanna@develop

getting the following 

 spack install savanna@develop
No command 'spack' found, did you mean:
 Command 'pack' from package 'liballegro4-dev' (universe)
 Command 'cpack' from package 'cmake' (main)
 Command 'apack' from package 'atool' (universe)
 Command 'slack' from package 'slack' (universe)
 Command 'mpack' from package 'mpack' (universe)
 Command 'spock' from package 'python-sardana' (universe)
 Command 'ipack' from package 'exult-studio' (multiverse)
 Command 'spark' from package 'spark' (universe)
spack: command not found

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc 

suggestion:

Add the following before **"spack install savanna@develop"**

EXPORT PATH:$PATH:~/spack/bin

**Comment by abidmalikwaterloo** [comment]
==> 'cmake' '/home/amalik/spack/var/spack/stage/libffs-1.1.1-u7dg3js7lh4phsuusb7txg2m7dxx3n7w/ffs-1.1.1' '-DCMAKE_INSTALL_PREFIX:PATH=/home/amalik/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/libffs-1.1.1-u7dg3js7lh4phsuusb7txg2m7dxx3n7w' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/home/amalik/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/libffs-1.1.1-u7dg3js7lh4phsuusb7txg2m7dxx3n7w/lib:/home/amalik/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/libffs-1.1.1-u7dg3js7lh4phsuusb7txg2m7dxx3n7w/lib64:/home/amalik/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/gtkorvo-atl-2.1-obzod3knr3iesegnhm62r4xjvelztdvq/lib:/home/amalik/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/gtkorvo-cercs-env-1.0-mi7osffjati4xggftwl3n5pfg3coxhed/lib:/home/amalik/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/gtkorvo-dill-2.1-ryxlbxp575svrnzdp5liabfuxvhttge2/lib' '-DENABLE_TESTING=0' '-DTARGET_CNL=1' '-DBUILD_SHARED_STATIC=STATIC'
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /home/amalik/spack/lib/spack/env/gcc/gcc
-- Check for working C compiler: /home/amalik/spack/lib/spack/env/gcc/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/amalik/spack/lib/spack/env/gcc/g++
-- Check for working CXX compiler: /home/amalik/spack/lib/spack/env/gcc/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of double
-- Check size of double - done
-- Check size of float
-- Check size of float - done
-- Check size of int
-- Check size of int - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of long
-- Check size of long - done
-- Check size of long double
-- Check size of long double - done
-- Check size of long long
-- Check size of long long - done
-- Check size of size_t
-- Check size of size_t - done
-- Looking for socket
-- Looking for socket - found
-- Could NOT find BISON (missing:  BISON_EXECUTABLE)
-- Found FLEX: /usr/bin/flex (found version "2.5.35")
CMake Error at CMakeLists.txt:103 (BISON_TARGET):
  Unknown CMake command "BISON_TARGET".


-- Configuring incomplete, errors occurred!

**Comment by kshitij-v-mehta** [comment]
Looks like you need to install bison on your machine using the package manager

**Comment by ianfoster** [comment]
Dear Abid:

I recommend following the instructions at https://github.com/CODARcode/Example-Heat_Transfer <https://github.com/CODARcode/Example-Heat_Transfer>, as they include installing Bison, etc.

Regards — Ian

**Comment by abidmalikwaterloo** [comment]
fixed it. I think I missed the step for bison.

**Comment by abidmalikwaterloo** [comment]
@kshitij-v-mehta @jychoi-hpc 

I ran the workflow as per instruction on the [github.](https://github.com/CODARcode/Example-Heat_Transfer) I am getting segmentation error due to "**The connection is being refused.. errno 111**"..

**Comment by mw70** [comment]
@abidmalik1967 Could you clarify what exactly is segfaulting?  Since it's saying it's a connection, I'm assuming it isn't in the build environment, and you are trying to run the configuration somehow.  Which transport are you using?  Which of the swift workflows?

**Comment by abidmalikwaterloo** [comment]
@mw70 : I am attaching a file showing the errors.

[out.txt](https://github.com/CODARcode/Example-Heat_Transfer/files/1170576/out.txt)

I used spack to build the savanna and then used run-workflow.sh script in the heat transfer to run the workflow. By default it takes "FLEXPATH" as transport. I am testing it on my local linux machine.

**Comment by kshitij-v-mehta** [comment]
Could you ensure you have enabled the FLEXPATH method in your xml file?

**Comment by abidmalikwaterloo** [comment]
I am attaching the file:

[heat_transfer.txt](https://github.com/CODARcode/Example-Heat_Transfer/files/1170671/heat_transfer.txt)


The other transports (MPI and dataspaces) are not being used. I am only using FLEXPATH.

**Comment by jychoi-hpc** [comment]
I cannot find any clue from your logs. Do you mind try the followings? 
1. Rebooting your vm (if you use a VM) 
2. Check if there is any remaining processes (`ps -ef | grep mpi`)
3. Uninstall and install savanna@develop and try again

**Comment by mw70** [comment]
@abidmalik1967 A quick response from Greg Eisenhauer -- error 111 means "connection refused".  Could you check whether you have firewalls turned on for your local machine?  The default connection used by Flexpath is TCP, since that is supported most everywhere, but if you have firewalls blocking the port, it won't work. 

The segfault is potentially a separate issue, but it may be that there's some failed cleanup in the case that connection was refused as opposed to simply being not available.  In which case fixing the fire wall should fix everything.

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc @mw70  It works with dataspaces.. Let me look into it further. Else I will install it again.

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc @mw70  able to run it on a Linux machine and a virtual machine. There was a problem in the BNL  Linux machine's configuration which was breaking the run of the heat flow example.

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc @kshitij-v-mehta Does savanna run with MPI? I can run it with FLEXPATH and Dataspaces ( using cheetah).

**Comment by kshitij-v-mehta** [comment]
I believe it was tested manually and did run successfully.

**Comment by mw70** [comment]
@abidmalik1967 Just a reminder that the MPI Adios method is an abbreviation of MPI-IO -- it does not directly connect using MPI, but instead uses MPI-IO files as an intermediate connection.  So it does work, but the workflow it uses is slightly different from the one in-memory connection methods.

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc @kshitij-v-mehta .. When I tried ./runworkflow.sh  16 MPI, it didn't work. I made changes in *.xml files before running. Did anyone try it using cheetah?

**Comment by jychoi-hpc** [comment]
"MPI" method has been added recently. Can you try again after uninstalling and installing savanna@develop? 

The most recent version of Heat transfer code will have git hash "df8112b".

**Comment by abidmalikwaterloo** [comment]
@jychoi-hpc It worked.  I noticed that the framework worked well with Ubuntu 16 and crashed with Ubuntu 14.
