### ISSUE TITLE
segfault if stage_write has wrong parameters

### ISSUE THREAD

**Issue by bd4** [CODARcode/Example-Heat_Transfer#2]
Running `stage_write/stage_write heat.pb staged.pb FLEXPATH MPI 2` causes a segfault. This is being triggered by a Cheetah bug that is loosing the empty parameters after FLEXPATH and MPI, but a better error messages for cases like this would be very helpful in debugging.

**Comment by jychoi-hpc** [comment]
Updated a line to check the minimum number of parameters in "stage_write". It simply check the number of parameters. If there are more complicated scenarios, we need to consider to use more sophisticated routines. Please let us know if this is enough at this moment.

**Comment by bd4** [comment]
Thanks, that is a ood short term solution, nothing more is needed short term. I do think deeper error checking would be good to add later though.
