### ISSUE TITLE
DATASPACES does not work?

### ISSUE THREAD

**Issue by ianfoster** [CODARcode/Example-Heat_Transfer#4]
I changed the rmethod in workflow.swift to DATASPACES:

      arguments2 = split("heat.bp staged.bp DATASPACES \"\" MPI \"\"", " ");

I am running with 1 process for Heat Equation and 1 process for Stage Write. I tried ./run-workflow with arguments of both 3 and 4, and I see the following

swift: launching: ./heat_transfer_adios2
size: 6
swift: launching: stage_write/stage_write
[rpc_read_config]: open config file failed!
[dc_register_at_master]: read RPC config file failed!
[dc_alloc]: register DART client failed!
[rpc_read_config]: open config file failed!
[dc_register_at_master]: read RPC config file failed!
[dc_alloc]: register DART client failed!
[dc_listen]: accept new connection failed, skip!
[dc_listen]: accept new connection failed, skip!
...

and also

Input stream            = heat.bp
Output stream           = staged.bp
Read method             = DATASPACES (id=3)
Read method parameters  = "max_chunk_size=100; app_id =32767; 
verbose= 3;poll_interval  =  100;"
Write method            = MPI
Write method parameters = ""
Variable to transform   = ""
Transform parameters    = ""
'dcg_alloc()': failed with -12.
common_dspaces_init(): failed to initialize.
ERROR: Failed to connect with DATASPACES
Waiting to open stream heat.bp...
'dcg_alloc()': failed with -12.
common_dspaces_init(): failed to initialize.
ERROR: Failed to connect with DATASPACES
ERROR: dspaces library was not properly initialized!
ERROR: dspaces library was not properly initialized!
ERROR: dspaces library was not properly initialized!
INFO : Data of 'heat.bp' does not exist (yet) in DataSpaces
ERROR: dspaces library was not properly initialized!
...

**Comment by philip-davis** [comment]
I created #6 to allow the dataspaces_server launch along along with heat_transfer and stage_write with an additional argument to run-workflow.sh. I documented this process as well.

**Comment by jychoi-hpc** [comment]
DataSpace support (#6) merged.

**Comment by philip-davis** [comment]
Resolved and pushed to master.
